name = "PolyhedralRelaxations"
uuid = "2e741578-48fa-11ea-2d62-b52c946f73a0"
authors = ["Kaarthik Sundar", "Sujeevraja Sanjeevi"]
version = "0.3.4"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"

[compat]
DataStructures = "~0.17, ~0.18"
ForwardDiff = "~0.5.0, ~0.6, ~0.7, ~0.8, ~0.9, ~0.10"
JuMP = "^0.21.0, ~0.22, ~0.23, ~1.0"
LoggingExtras = "0.4.7, 0.5"
julia = "1"

[extras]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Cbc", "Ipopt", "Test"]
